=== vambra/saitynoPraktinis/projectData.dtd
<!ELEMENT projectList (project)*>
<!ELEMENT project (character|source|dueDate|startDate|finishDate|budget|componentList|conventionList)*>
<!ELEMENT character (#PCDATA)>
<!ELEMENT source (#PCDATA)>
<!ELEMENT dueDate (#PCDATA)>
<!ELEMENT startDate (#PCDATA)>
<!ELEMENT finishDate (#PCDATA)>
<!ELEMENT budget (#PCDATA)>
<!ELEMENT componentList (component)*>
<!ELEMENT component (name|cost|taskList)*>
<!ELEMENT name (#PCDATA)>
<!ELEMENT cost (#PCDATA)>
<!ELEMENT taskList (task)*>
<!ELEMENT task (name|progress|timeElapsedHours|timeElapsedMinutes)*>
<!ELEMENT progress (#PCDATA)>
<!ELEMENT timeElapsedHours (#PCDATA)>
<!ELEMENT timeElapsedMinutes (#PCDATA)>
<!ELEMENT conventionList (convention)*>
<!ELEMENT convention (name|date|competitionList)*>
<!ELEMENT date (#PCDATA)>
<!ELEMENT competitionList (competition)*>
<!ELEMENT competition (category|award|prize)*>
<!ELEMENT category (#PCDATA)>
<!ELEMENT award (#PCDATA)>
<!ELEMENT prize (#PCDATA)>

=== vambra/saitynoPraktinis/projectDataDTD.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE projectList SYSTEM "projectData.dtd">
<projectList>
    <project>
        <character>Redeye Watcher</character>
        <source>Horizon Zero Dawn</source>
        <dueDate>2024-08-01</dueDate>
        <startDate>2019-11-01</startDate>
        <finishDate></finishDate>
        <budget>600.0</budget>
        <componentList>
            <component>
                <name>Head</name>
                <cost>0.0</cost>
                <taskList>
                    <task>
                        <name>Blueprint</name>
                        <progress>50</progress>
                        <timeElapsedHours>5</timeElapsedHours>
                        <timeElapsedMinutes>0</timeElapsedMinutes>
                    </task>
                    <task>
                        <name>Frame</name>
                        <progress>0</progress>
                        <timeElapsedHours>0</timeElapsedHours>
                        <timeElapsedMinutes>0</timeElapsedMinutes>
                    </task>
                    <task>
                        <name>LED circuit</name>
                        <progress>0</progress>
                        <timeElapsedHours>0</timeElapsedHours>
                        <timeElapsedMinutes>0</timeElapsedMinutes>
                    </task>
                    <task>
                        <name>Cover</name>
                        <progress>0</progress>
                        <timeElapsedHours>0</timeElapsedHours>
                        <timeElapsedMinutes>0</timeElapsedMinutes>
                    </task>
                </taskList>
            </component>
            <component>
                <name>Neck</name>
                <cost>0.0</cost>
                <taskList>
                    <task>
                        <name>Blueprint</name>
                        <progress>50</progress>
                        <timeElapsedHours>5</timeElapsedHours>
                        <timeElapsedMinutes>0</timeElapsedMinutes>
                    </task>
                    <task>
                        <name>Frame</name>
                        <progress>0</progress>
                        <timeElapsedHours>0</timeElapsedHours>
                        <timeElapsedMinutes>0</timeElapsedMinutes>
                    </task>
                    <task>
                        <name>LED circuit</name>
                        <progress>0</progress>
                        <timeElapsedHours>0</timeElapsedHours>
                        <timeElapsedMinutes>0</timeElapsedMinutes>
                    </task>
                    <task>
                        <name>Cover</name>
                        <progress>0</progress>
                        <timeElapsedHours>0</timeElapsedHours>
                        <timeElapsedMinutes>0</timeElapsedMinutes>
                    </task>
                </taskList>
            </component>
            <component>
                <name>Body</name>
                <cost>0.0</cost>
                <taskList>
                    <task>
                        <name>Blueprint</name>
                        <progress>50</progress>
                        <timeElapsedHours>5</timeElapsedHours>
                        <timeElapsedMinutes>0</timeElapsedMinutes>
                    </task>
                    <task>
                        <name>Frame</name>
                        <progress>0</progress>
                        <timeElapsedHours>0</timeElapsedHours>
                        <timeElapsedMinutes>0</timeElapsedMinutes>
                    </task>
                    <task>
                        <name>Cover</name>
                        <progress>0</progress>
                        <timeElapsedHours>0</timeElapsedHours>
                        <timeElapsedMinutes>0</timeElapsedMinutes>
                    </task>
                </taskList>
            </component>
            <component>
                <name>Legs</name>
                <cost>30.0</cost>
                <taskList>
                    <task>
                        <name>Blueprint</name>
                        <progress>50</progress>
                        <timeElapsedHours>5</timeElapsedHours>
                        <timeElapsedMinutes>0</timeElapsedMinutes>
                    </task>
                    <task>
                        <name>Frame</name>
                        <progress>0</progress>
                        <timeElapsedHours>0</timeElapsedHours>
                        <timeElapsedMinutes>0</timeElapsedMinutes>
                    </task>
                    <task>
                        <name>LED circuit</name>
                        <progress>0</progress>
                        <timeElapsedHours>0</timeElapsedHours>
                        <timeElapsedMinutes>0</timeElapsedMinutes>
                    </task>
                    <task>
                        <name>Cover</name>
                        <progress>0</progress>
                        <timeElapsedHours>0</timeElapsedHours>
                        <timeElapsedMinutes>0</timeElapsedMinutes>
                    </task>
                </taskList>
            </component>
            <component>
                <name>Tail</name>
                <cost>30.0</cost>
                <taskList>
                    <task>
                        <name>Blueprint</name>
                        <progress>50</progress>
                        <timeElapsedHours>5</timeElapsedHours>
                        <timeElapsedMinutes>0</timeElapsedMinutes>
                    </task>
                    <task>
                        <name>Frame</name>
                        <progress>0</progress>
                        <timeElapsedHours>0</timeElapsedHours>
                        <timeElapsedMinutes>0</timeElapsedMinutes>
                    </task>
                    <task>
                        <name>LED circuit</name>
                        <progress>0</progress>
                        <timeElapsedHours>0</timeElapsedHours>
                        <timeElapsedMinutes>0</timeElapsedMinutes>
                    </task>
                    <task>
                        <name>Cover</name>
                        <progress>0</progress>
                        <timeElapsedHours>0</timeElapsedHours>
                        <timeElapsedMinutes>0</timeElapsedMinutes>
                    </task>
                </taskList>
            </component>
        </componentList>
        <conventionList>
            <convention>
                <name>Comic Con Baltics</name>
                <date>2021-07-11</date>
                <competitionList>
                    <competition>
                        <category>Solo</category>
                        <award>Judge's favourite</award>
                        <prize>merchandise, ticket to CCB 2022</prize>
                    </competition>
                </competitionList>
            </convention>
        </conventionList>
    </project>
    <project>
        <character>Scaramouche</character>
        <source>Genshin Impact</source>
        <dueDate>2021-05-01</dueDate>
        <startDate>2020-11-01</startDate>
        <finishDate>2021-04-24</finishDate>
        <budget>100</budget>
        <componentList>
            <component>
                <name>Hat</name>
                <cost>40.0</cost>
                <taskList>
                    <task>
                        <name>Blueprint</name>
                        <progress>100</progress>
                        <timeElapsedHours>3</timeElapsedHours>
                        <timeElapsedMinutes>0</timeElapsedMinutes>
                    </task>
                    <task>
                        <name>Base</name>
                        <progress>100</progress>
                        <timeElapsedHours>6</timeElapsedHours>
                        <timeElapsedMinutes>15</timeElapsedMinutes>
                    </task>
                    <task>
                        <name>Painting</name>
                        <progress>100</progress>
                        <timeElapsedHours>2</timeElapsedHours>
                        <timeElapsedMinutes>0</timeElapsedMinutes>
                    </task>
                </taskList>
            </component>
            <component>
                <name>Kimono</name>
                <cost>15.0</cost>
                <taskList>
                    <task>
                        <name>Pattern</name>
                        <progress>100</progress>
                        <timeElapsedHours>2</timeElapsedHours>
                        <timeElapsedMinutes>0</timeElapsedMinutes>
                    </task>
                    <task>
                        <name>Torso</name>
                        <progress>100</progress>
                        <timeElapsedHours>2</timeElapsedHours>
                        <timeElapsedMinutes>0</timeElapsedMinutes>
                    </task>
                    <task>
                        <name>Sleeve detailing</name>
                        <progress>0</progress>
                        <timeElapsedHours>3</timeElapsedHours>
                        <timeElapsedMinutes>0</timeElapsedMinutes>
                    </task>
                </taskList>
            </component>
            <component>
                <name>Shorts</name>
                <cost>10.0</cost>
                <taskList>
                    <task>
                        <name>Pattern</name>
                        <progress>100</progress>
                        <timeElapsedHours>0</timeElapsedHours>
                        <timeElapsedMinutes>40</timeElapsedMinutes>
                    </task>
                    <task>
                        <name>Sewing</name>
                        <progress>0</progress>
                        <timeElapsedHours>0</timeElapsedHours>
